services:

  app:
    image: alejoide/alejoide-web:latest
    container_name: alejoide-app
    restart: unless-stopped
    env_file:
      - ./config/.app.env
    volumes:
      - static:/app/.web/_static
    networks:
      - default
      - nginx-proxy


  webserver:
    image: nginx:latest
    container_name: alejoide-webserver
    restart: unless-stopped
    env_file:
      - ./config/.webserver.env
    volumes:
      - static:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - default
      - nginx-proxy


  metrics-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: prometheus-nginx-exporter
    restart: unless-stopped
    command:
      - -nginx.scrape-uri=http://webserver:8080/metrics
    expose:
      - 9113
    networks:
      - default
      - metrics


volumes:
  static:

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
  metrics:
